# aws_elb_name_etcd_visible                 = "visible-etcd-internal"
# aws_security_group_elb_etcd_visible_id    = "sg-51782b34"
aws_elb_name_vulcand_visible              = "visible-vulcand-external"
aws_security_group_elb_vulcand_visible_id = "sg-ae0052cb"
aws_elb_name_gtin_visible                 = "visible-gtin-external"
aws_security_group_elb_gtin_visible_id    = "sg-af0052ca"
